name: 🐛 Sdenv Bug 反馈
description: 如发现 Sdenv 框架中的 Bug，请及时在此汇报。
labels: [bug]
body:
  - type: textarea
    attributes:
      label: |
        在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：
      placeholder: |
        1. 我做了什么。

        2. 我的预期值。

        3. 我实际得到的结果。

        4. 可以的话，请提供一些截图、视频作为附件以复现症状。
    validations:
      required: true
  - type: input
    attributes:
      label: Node 版本号：
      description: |
        你的当前复现问题的 Node 版本号：
      placeholder: |
        使用 “node -v” 命令，在控制台得到版本号（例如：v8.5.0）。
    validations:
      required: true
  - type: input
    attributes:
      label: "操作平台与版本号（Platform and Version）："
      description: |
        你的操作平台与版本号：
      placeholder: |
        Windows 10 专业版（21H2）
    validations:
      required: true
